# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='operator',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('/', '/'), ('X', 'X')], max_length=1),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='result',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
