# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0002_auto_20161017_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculation',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='result',
        ),
    ]
